name: 'Disable Git Compression'
description: 'Sets configurations, such as core.compression, to 0'
branding:
  icon: 'fast-forward'  
  color: 'red'

runs:
  using: "composite"
  steps:
#    shell: bash
    run: |
      sudo git config --system core.compression 0
      sudo git config --system core.looseCompression 0
      sudo git config --system checkout.workers -1
      sudo git config --system pack.compression 0
      
